[2022-09-20T18:58:39.408+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: booking_ingestion.transform_data manual__2022-09-20T18:58:38.300201+00:00 [queued]>
[2022-09-20T18:58:39.415+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: booking_ingestion.transform_data manual__2022-09-20T18:58:38.300201+00:00 [queued]>
[2022-09-20T18:58:39.416+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-20T18:58:39.416+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-20T18:58:39.417+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-20T18:58:39.424+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform_data> on 2022-09-20 18:58:38.300201+00:00
[2022-09-20T18:58:39.428+0000] {standard_task_runner.py:54} INFO - Started process 102 to run task
[2022-09-20T18:58:39.431+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'transform_data', 'manual__2022-09-20T18:58:38.300201+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/main.py', '--cfg-path', '/tmp/tmpdzuw6wau']
[2022-09-20T18:58:39.433+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask transform_data
[2022-09-20T18:58:39.435+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_dag/main.py
[2022-09-20T18:58:39.650+0000] {task_command.py:384} INFO - Running <TaskInstance: booking_ingestion.transform_data manual__2022-09-20T18:58:38.300201+00:00 [running]> on host 3756ba1ca570
[2022-09-20T18:58:39.667+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:191: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-20T18:58:39.690+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T18:58:38.300201+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-20T18:58:38.300201+00:00
[2022-09-20T18:58:39.691+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 33, in transform_data
    print(os.listdir('dir_path'))
FileNotFoundError: [Errno 2] No such file or directory: 'dir_path'
[2022-09-20T18:58:39.698+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=transform_data, execution_date=20220920T185838, start_date=20220920T185839, end_date=20220920T185839
[2022-09-20T18:58:39.704+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task transform_data ([Errno 2] No such file or directory: 'dir_path'; 102)
[2022-09-20T18:58:39.727+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-20T18:58:39.747+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
