[2022-09-22T05:19:27.535+0000] {processor.py:156} INFO - Started process (PID=36) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:19:27.536+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:19:27.538+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:19:27.538+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:19:28.308+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:19:28.301+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:19:28.311+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:19:28.331+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.799 seconds
[2022-09-22T05:19:58.520+0000] {processor.py:156} INFO - Started process (PID=67) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:19:58.523+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:19:58.525+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:19:58.525+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:19:58.684+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:19:58.681+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:19:58.685+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:19:58.700+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.185 seconds
[2022-09-22T05:20:28.905+0000] {processor.py:156} INFO - Started process (PID=99) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:20:28.906+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:20:28.907+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:20:28.907+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:20:29.029+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:20:29.027+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:20:29.031+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:20:29.043+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.140 seconds
[2022-09-22T05:20:59.265+0000] {processor.py:156} INFO - Started process (PID=132) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:20:59.267+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:20:59.269+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:20:59.268+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:20:59.406+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:20:59.403+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:20:59.408+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:20:59.426+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.163 seconds
[2022-09-22T05:28:43.309+0000] {processor.py:156} INFO - Started process (PID=36) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:28:43.310+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:28:43.312+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:28:43.312+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:28:43.894+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:28:43.883+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:28:43.896+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:28:43.944+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.641 seconds
[2022-09-22T05:29:14.101+0000] {processor.py:156} INFO - Started process (PID=71) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:29:14.104+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:29:14.105+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:29:14.105+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:29:14.383+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:29:14.381+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:29:14.385+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:29:14.398+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.299 seconds
[2022-09-22T05:29:44.605+0000] {processor.py:156} INFO - Started process (PID=101) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:29:44.607+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:29:44.610+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:29:44.610+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:29:44.814+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:29:44.811+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:29:44.815+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:29:44.826+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.225 seconds
[2022-09-22T05:30:15.090+0000] {processor.py:156} INFO - Started process (PID=133) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:30:15.091+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:30:15.092+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:30:15.092+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:30:15.329+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:30:15.327+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:30:15.330+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:30:15.341+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.255 seconds
[2022-09-22T05:39:05.789+0000] {processor.py:156} INFO - Started process (PID=146) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:39:05.790+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:39:05.791+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:39:05.791+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:39:06.024+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:39:06.022+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:39:06.026+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:39:06.037+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.251 seconds
[2022-09-22T05:39:36.312+0000] {processor.py:156} INFO - Started process (PID=177) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:39:36.314+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:39:36.315+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:39:36.315+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:39:36.553+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:39:36.551+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:39:36.555+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:39:36.567+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.257 seconds
[2022-09-22T05:40:00.419+0000] {processor.py:156} INFO - Started process (PID=36) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:40:00.423+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:40:00.424+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:40:00.424+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:40:01.110+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:40:01.107+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:40:01.113+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:40:01.137+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.722 seconds
[2022-09-22T05:40:31.510+0000] {processor.py:156} INFO - Started process (PID=68) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:40:31.512+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:40:31.514+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:40:31.514+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:40:31.651+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:40:31.648+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:40:31.653+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:40:31.668+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.161 seconds
[2022-09-22T05:41:01.851+0000] {processor.py:156} INFO - Started process (PID=100) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:41:01.854+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:41:01.856+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:41:01.856+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:41:01.988+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:41:01.986+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:41:01.993+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:41:02.005+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.158 seconds
[2022-09-22T05:41:32.232+0000] {processor.py:156} INFO - Started process (PID=133) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:41:32.237+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:41:32.243+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:41:32.242+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:41:32.899+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:41:32.890+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:41:32.901+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:41:32.949+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.720 seconds
[2022-09-22T05:42:03.188+0000] {processor.py:156} INFO - Started process (PID=156) to work on /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:42:03.191+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/data_ingestion_dag/main.py for tasks to queue
[2022-09-22T05:42:03.193+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:42:03.193+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:42:03.337+0000] {logging_mixin.py:117} INFO - [2022-09-22T05:42:03.334+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_dag/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 17, in <module>
    sys.append('./scripts')
AttributeError: module 'sys' has no attribute 'append'
[2022-09-22T05:42:03.339+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_dag/main.py
[2022-09-22T05:42:03.353+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/data_ingestion_dag/main.py took 0.170 seconds
